<?php
        Route::controller('pages', 'PagesController');
                    Route::controller('vendor', 'VendorController');
                    Route::controller('calendar', 'CalendarController');
                    Route::controller('sbinovice', 'SbinoviceController');
                    Route::controller('sbinvoiceitem', 'SbinvoiceitemController');
                    Route::controller('sbproduct', 'SbproductController');
                    Route::controller('employee', 'EmployeeController');
                    Route::controller('customer', 'CustomerController');
                    Route::controller('orderdetail', 'OrderdetailController');
                    Route::controller('product', 'ProductController');
                    Route::controller('reports', 'ReportsController');
                    Route::controller('sbticket', 'SbticketController');
                    Route::controller('topgame', 'TopgameController');
                    Route::controller('bottomgame', 'BottomgameController');
                    Route::controller('department', 'DepartmentController');
                    Route::controller('location', 'LocationController');
                    Route::controller('game', 'GameController');
                    Route::controller('gamesdown', 'GamesdownController');
                    Route::controller('ticketcomment', 'TicketcommentController');
                    Route::controller('gamestitle', 'GamestitleController');
                    Route::controller('order', 'OrderController');
                    Route::controller('pendingrequest', 'PendingrequestController');
                    Route::controller('tablecols', 'TablecolsController');
                    Route::controller('mylocationgame', 'MylocationgameController');
                    Route::controller('merchandisebudget', 'MerchandisebudgetController');
<<<<<<< HEAD
                    Route::controller('shopfegrequeststore', 'ShopfegrequeststoreController');
=======
                    Route::controller('closedlocations', 'ClosedlocationsController');
                    Route::controller('gamesnotondebitcard', 'GamesnotondebitcardController');
                    Route::controller('closedlocationstwo', 'ClosedlocationstwoController');
                    Route::controller('topgamesavgplays', 'TopgamesavgplaysController');
                    Route::controller('bottomgamesavgplays', 'BottomgamesavgplaysController');
                    Route::controller('potentialoverreportingerrors', 'PotentialoverreportingerrorsController');
                    Route::controller('gameplayrankbylocation', 'GameplayrankbylocationController');
                    Route::controller('gamesnotplayed', 'GamesnotplayedController');
                    Route::controller('nonfegreaders', 'NonfegreadersController');
                    Route::controller('merchthrowssimple', 'MerchthrowssimpleController');
                    Route::controller('merchthrowsdetailed', 'MerchthrowsdetailedController');
>>>>>>> 4e24e08860493d4b9b54fa722d1f4079a39432fa
                    ?>